#Defines or set active application profile: live or development
spring.profiles.active: test

---

spring:
  profiles: live
  application.name: DroneService
  h2.console.enabled: true
  servlet:
    multipart.enabled: true
    multipart.file-size-threshold: 2KB
    multipart.max-file-size: 200MB
    multipart.max-request-size: 215MB

  datasource:
    url: jdbc:h2:file:./data/drone-data
    username: droneservice
    password: droneservice
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

file:
  upload-dir: file:///${project.basedir}/uploads

logging:
  file: logs/application.log
  file.max-size: 200MB
  level:
    org.apache.http: INFO
    org.springframework.cloud.sleuth: INFO
    org.springframework.web: INFO
    com.netflix.discovery.DiscoveryClient: INFO
    com.drone.manager: INFO
    org.springframework.security: INFO
environment: live
server.port: 8084

---

spring:
  profiles: test
  application.name: DroneService
  h2.console.enabled: true
  servlet:
    multipart.enabled: true
    multipart.file-size-threshold: 2KB
    multipart.max-file-size: 200MB
    multipart.max-request-size: 215MB

  datasource:
    url: jdbc:h2:file:./data/drone-data
    username: droneservice
    password: droneservice
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

file:
  upload-dir: file:///${project.basedir}/uploads

logging:
  file: logs/application.log
  file.max-size: 200MB
  level:
    org.apache.http: INFO
    org.springframework.cloud.sleuth: INFO
    org.springframework.web: INFO
    com.netflix.discovery.DiscoveryClient: INFO
    com.drone.manager: INFO
    org.springframework.security: INFO
environment: test
server.port: 8084